# Generated by Django 2.2.1 on 2019-07-09 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2019, 7, 9, 20, 22, 50, 314298))),
                ('number_of_pages', models.IntegerField(default=0)),
                ('is_first_edition', models.BooleanField(default=True)),
            ],
        ),
    ]
