# Generated by Django 2.2.1 on 2019-07-14 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('ER', 'Engineering'), ('ME', 'Medical'), ('AR', 'Art'), ('PS', 'Psychology')], default='ER', max_length=2),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 17, 0, 45, 554321)),
        ),
    ]
