# Generated by Django 2.2.1 on 2019-07-16 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190714_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2019, 7, 16, 15, 2, 49, 966203)),
        ),
    ]
